=== Tauron32/LabBBDD/dbtoxml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <xs:element name="db_schema" type="database_schema_type"/>

    <xs:simpleType name="cons_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="C"/>
            <xs:enumeration value="P"/>
            <xs:enumeration value="R"/>
            <xs:enumeration value="U"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="nullable_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Y"/>
            <xs:enumeration value="N"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="cons_column">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="position" type="xs:integer"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="constraint_type">
        <xs:sequence>
            <xs:element name="type" type="cons_type"></xs:element>
            <xs:choice> 
                <xs:element name="search_condition" type="xs:string"/>
                <xs:element name="pk_members" type="pk_cons"/>
                <xs:element name="fk_members" type="fk_cons" />
                <xs:element name="unique_members" type="unique_cons" />
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="idcons" type="xs:string" use="required"/>
    </xs:complexType>

    
    <xs:complexType name="pk_cons">
        <xs:sequence>
            <xs:element name="column" type="cons_column" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="unique_cons">
        <xs:sequence>
            <xs:element name="column" type="cons_column" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="fk_cons">
        <xs:sequence>
            <xs:element name="column" type="cons_column" maxOccurs="unbounded"/>
            <xs:element name="references" type="ref_type"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ref_type">
        <xs:sequence>
            <xs:element name="ref_table_name" type="xs:string"/>
            <xs:element name="ref_constraint" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="column_type">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="data_type" type="xs:string"/>
            <xs:element name="nullable" type="nullable_type"></xs:element>
        </xs:sequence>
        <xs:attribute name="idcol" type="xs:string" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="table_type">
        <xs:sequence>                
            <xs:element name="name" type="xs:string"/>
            <xs:element name="column" type="column_type" maxOccurs="unbounded"/>
            <xs:element name="constraint" type="constraint_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="idtab" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="database_schema_type">
        <xs:sequence>
            <xs:element name="table" type="table_type" maxOccurs="unbounded">
                <xs:key name="col_name">
                    <xs:selector xpath="./column"/>
                    <xs:field xpath="name"/>
                </xs:key>
                <xs:keyref refer="col_name" name="cons_col_name">
                    <xs:selector xpath="./constraint/*/column/name"></xs:selector>
                    <xs:field xpath="."></xs:field>
                </xs:keyref>
                <xs:unique name="u_table_id">
                    <xs:selector xpath="."/>
                    <xs:field xpath="@idtab"/>
                </xs:unique>
                <xs:unique name="u_cons_id">
                    <xs:selector xpath="."/>
                    <xs:field xpath="@idcons"/>
                </xs:unique>
                <xs:unique name="u_table_name">
                    <xs:selector xpath="."/>
                    <xs:field xpath="name"/>
                </xs:unique>
                <xs:unique name="u_cons_name">
                    <xs:selector xpath="./constraint"/>
                    <xs:field xpath="name"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Tauron32/LabBBDD/xml_data.xml
<db_schema 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="dbtoxml.xsd">

	<table idtab="1">
		<name>CENTROS</name>
		<column idcol="11">
			<name>NUMERO</name>
			<data_type>NUMBER</data_type>
			<nullable>N</nullable>
		</column>
		<column idcol="12">
			<name>NOMBRE</name>
			<data_type>VARCHAR2(30)</data_type>
			<nullable>N</nullable>
		</column>
		<column idcol="13">
			<name>DIRECCION</name>
			<data_type>VARCHAR2(50)</data_type>
			<nullable>Y</nullable>
		</column>
		<constraint idcons="XML_SYS_C0048897">
			<type>C</type>
			<search_condition>"NOMBRE" IS NOT NULL</search_condition>
		</constraint>
		<constraint idcons="XML_SYS_C0048898">
			<type>P</type>
			<pk_members>
				<column position="1">NUMERO</column>
			</pk_members>
		</constraint>
	</table>

	<table idtab="2">
		<name>DEPARTAMENTOS</name>
		<column idcol="21">
			<name>NUMERO</name>
			<data_type>NUMBER</data_type>
			<nullable>N</nullable>
		</column>
		<column idcol="22">
			<name>CENTRO</name>
			<data_type>NUMBER</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="23">
			<name>DIRECCION</name>
			<data_type>NUMBER</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="24">
			<name>TIPO_DIR</name>
			<data_type>CHAR</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="25">
			<name>PRESUPUESTO</name>
			<data_type>NUMBER</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="26">
			<name>DEPTO_JEFE</name>
			<data_type>NUMBER</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="27">
			<name>NOMBRE</name>
			<data_type>VARCHAR2(20)</data_type>
			<nullable>Y</nullable>
		</column>
		<constraint idcons="XML_SYS_C0048899">
			<type>C</type>
			<search_condition>TIPO_DIR IN ('P','F')</search_condition>
		</constraint>
		<constraint idcons="XML_SYS_C0048900">
			<type>P</type>
			<pk_members>
				<column position="1">NUMERO</column>
			</pk_members>
		</constraint>
		<constraint idcons="XML_SYS_C0048901">
			<type>R</type>
			<fk_members>
				<column position="1">CENTRO</column>
				<references>
					<ref_table_name>CENTROS</ref_table_name>
					<ref_constraint>XML_SYS_C0048898</ref_constraint>
				</references>
			</fk_members>
		</constraint>
		<constraint idcons="JERARQUIA_DPTOS">
			<type>R</type>
			<fk_members>
				<column position="1">DEPTO_JEFE</column>
				<references>
					<ref_table_name>DEPARTAMENTOS</ref_table_name>
					<ref_constraint>XML_SYS_C0048900</ref_constraint>
				</references>
			</fk_members>
		</constraint>
	</table>

	<table idtab="3">
		<name>EMPLEADOS</name>
		<column idcol="31">
			<name>NUMERO</name>
			<data_type>NUMBER</data_type>
			<nullable>N</nullable>
		</column>
		<column idcol="32">
			<name>DEPARTAMENTO</name>
			<data_type>NUMBER</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="33">
			<name>TELEFONO</name>
			<data_type>NUMBER</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="34">
			<name>FECHA_NACIMIENTO</name>
			<data_type>DATE</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="35">
			<name>FECHA_INGRESO</name>
			<data_type>DATE</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="36">
			<name>SALARIO</name>
			<data_type>NUMBER</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="37">
			<name>COMISION</name>
			<data_type>NUMBER</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="38">
			<name>NUM_HIJOS</name>
			<data_type>NUMBER</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="39">
			<name>NOMBRE</name>
			<data_type>VARCHAR2(20)</data_type>
			<nullable>N</nullable>
		</column>
		<column idcol="40">
			<name>DNI</name>
			<data_type>NUMBER</data_type>
			<nullable>Y</nullable>
		</column>
		<constraint idcons="XML_SYS_C0048903">
			<type>C</type>
			<search_condition>"NOMBRE" IS NOT NULL</search_condition>
		</constraint>
		<constraint idcons="XML_SYS_C0048904">
			<type>P</type>
			<pk_members>
				<column position="1">NUMERO</column>
			</pk_members>
		</constraint>
		<constraint idcons="XML_SYS_C0048905">
			<type>U</type>
			<unique_members>
				<column position="1">DNI</column>
			</unique_members>
		</constraint>
		<constraint idcons="XML_SYS_C0048906">
			<type>R</type>
			<fk_members>
				<column position="1">DEPARTAMENTO</column>
				<references>
					<ref_table_name>DEPARTAMENTOS</ref_table_name>
					<ref_constraint>XML_SYS_C0048900</ref_constraint>
				</references>
			</fk_members>
		</constraint>
	</table>

	<table idtab="4">
		<name>VISITAR</name>
		<column idcol="41">
			<name>EMPLEADO</name>
			<data_type>NUMBER</data_type>
			<nullable>N</nullable>
		</column>
		<column idcol="42">
			<name>DEPARTAMENTO</name>
			<data_type>NUMBER</data_type>
			<nullable>N</nullable>
		</column>
		<constraint idcons="XML_SYS_C0048907">
			<type>P</type>
			<pk_members>
				<column position="1">EMPLEADO</column>
				<column position="2">DEPARTAMENTO</column>
			</pk_members>
		</constraint>
		<constraint idcons="XML_SYS_C0048908">
			<type>R</type>
			<fk_members>
				<column position="1">EMPLEADO</column>
				<references>
					<ref_table_name>EMPLEADOS</ref_table_name>
					<ref_constraint>XML_SYS_C0048904</ref_constraint>
				</references>
			</fk_members>
		</constraint>
		<constraint idcons="XML_SYS_C0048909">
			<type>R</type>
			<fk_members>
				<column position="1">DEPARTAMENTO</column>
				<references>
					<ref_table_name>DEPARTAMENTOS</ref_table_name>
					<ref_constraint>XML_SYS_C0048900</ref_constraint>
				</references>
			</fk_members>
		</constraint>
	</table>

	<table idtab="5">
		<name>PRUEBAS</name>
		<column idcol="51">
			<name>XML</name>
			<data_type>CLOB</data_type>
			<nullable>Y</nullable>
		</column>
	</table>

	<table idtab="6">
		<name>OTRAS_PRUEBAS</name>
		<column idcol="61">
			<name>NUM</name>
			<data_type>NUMBER</data_type>
			<nullable>N</nullable>
		</column>
		<column idcol="62">
			<name>NOMBRE</name>
			<data_type>VARCHAR2(20)</data_type>
			<nullable>N</nullable>
		</column>
		<constraint idcons="PK_O">
			<type>P</type>
			<pk_members>
				<column position="1">NUM</column>
				<column position="2">NOMBRE</column>
			</pk_members>
		</constraint>
	</table>

	<table idtab="7">
		<name>MAS_PRUEBAS</name>
		<column idcol="71">
			<name>PK</name>
			<data_type>NUMBER</data_type>
			<nullable>N</nullable>
		</column>
		<column idcol="72">
			<name>A_OTRAS_PRUEBAS</name>
			<data_type>NUMBER</data_type>
			<nullable>Y</nullable>
		</column>
		<column idcol="73">
			<name>OTRO_NOMBRE</name>
			<data_type>VARCHAR2(20)</data_type>
			<nullable>Y</nullable>
		</column>
		<constraint idcons="XML_SYS_C0051274">
			<type>P</type>
			<pk_members>
				<column position="1">PK</column>
			</pk_members>
		</constraint>
		<constraint idcons="FK">
			<type>R</type>
			<fk_members>
				<column position="1">A_OTRAS_PRUEBAS</column>
				<column position="2">OTRO_NOMBRE</column>
				<references>
					<ref_table_name>OTRAS_PRUEBAS</ref_table_name>
					<ref_constraint>PK_O</ref_constraint>
				</references>
			</fk_members>
		</constraint>
	</table>

	<table idtab="8">
		<name>NUEVA_TABLA</name>
		<column idcol="81">
			<name>XML</name>
			<data_type>CLOB</data_type>
			<nullable>Y</nullable>
		</column>
	</table>

	<table idtab="9">
		<name>XML_SCHEMA</name>
		<column idcol="91">
			<name>XML</name>
			<data_type>CLOB</data_type>
			<nullable>Y</nullable>
		</column>
	</table>

</db_schema>
